# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\x12\tdetection\"\x1b\n\x05\x46rame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"R\n\tDetection\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x05 \x01(\x05\"=\n\x11\x44\x65tectionResponse\x12(\n\ndetections\x18\x01 \x03(\x0b\x32\x14.detection.Detection2T\n\x0bYOLOService\x12\x45\n\x0fStreamDetection\x12\x10.detection.Frame\x1a\x1c.detection.DetectionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=30
  _globals['_FRAME']._serialized_end=57
  _globals['_DETECTION']._serialized_start=59
  _globals['_DETECTION']._serialized_end=141
  _globals['_DETECTIONRESPONSE']._serialized_start=143
  _globals['_DETECTIONRESPONSE']._serialized_end=204
  _globals['_YOLOSERVICE']._serialized_start=206
  _globals['_YOLOSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
