[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["python312", "libGL"] # You can use python311 or python310 if needed

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python server.py"
